spring.application.name=backend-java

spring.datasource.url=jdbc:postgresql://localhost:5432/spotify_db
spring.datasource.username=postgresql
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update

spring.docker.compose.enabled=false

spring.profiles.active=dev